### ISSUE TITLE
Bot tried to delete messages that were mistakenly cached after reauth

### ISSUE THREAD

**Issue by ilovecherries** [ilovecherries/discord-sbs-bridge#13]
```
(Re)Starting WebSocket
authenticated
/app/node_modules/discord.js/src/rest/RequestHandler.js:298
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Unknown Message
    at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async Webhook.deleteMessage (/app/node_modules/discord.js/src/structures/Webhook.js:301:5) {
  method: 'delete',
  path: 'XXX',
  code: 10008,
  httpStatus: 404,
  requestData: { json: undefined, files: [] }
}
```

**Comment by ilovecherries** [comment]
it happened again
```
Error: Unable to find cached message
    at ChannelPair.getCachedDiscordMessage (/app/src/ChannelPair.js:70:19)
    at /app/src/bot.js:183:41
    at new Promise (<anonymous>)
    at SBSBridgeBot.getSBSMessage (/app/src/bot.js:178:16)
    at SBSBridgeBot.onDelete (/app/src/bot.js:78:18)
    at SBSBridgeBot.emit (node:events:394:28)
    at MessageDeleteAction.handle (/app/node_modules/discord.js/src/client/actions/MessageDelete.js:21:16)
    at Object.module.exports [as MESSAGE_DELETE] (/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_DELETE.js:4:32)
    at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
(Re)Starting WebSocket
authenticated
/app/node_modules/discord.js/src/rest/RequestHandler.js:298
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Unknown Message
    at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async Webhook.deleteMessage (/app/node_modules/discord.js/src/structures/Webhook.js:301:5) {
  method: 'delete',
  path: 'XXX',
  code: 10008,
  httpStatus: 404,
  requestData: { json: undefined, files: [] }
}
```

**Comment by ilovecherries** [comment]
i should *really* properly fix this thing up, this was before i knew how to do database stuff and this assoc thing is basically a hack
